# Generated by Django 5.2.4 on 2025-12-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='max_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
